# Generated by Django 5.0.4 on 2024-04-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_street_address_addressmodel_address'),
        ('buyer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registermodel')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.productmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
