# Generated by Django 5.0.4 on 2024-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_registermodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='is_added_address',
            field=models.BooleanField(default=False),
        ),
    ]
