# Generated by Django 5.0.4 on 2024-04-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_addressmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='customer_id',
            new_name='c_id',
        ),
    ]
